//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.carts = new HashSet<cart>();
            this.sub_order = new HashSet<sub_order>();
        }
    
        public int ISBN { get; set; }
        public string Title { get; set; }
        public string Version { get; set; }
        public string Language { get; set; }
        public Nullable<float> Price { get; set; }
        public string Year { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Image { get; set; }
        public string conclution { get; set; }
        public int Author_id { get; set; }
        public int Publisher_id { get; set; }
    
        public virtual author author { get; set; }
        public virtual publisher publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_order> sub_order { get; set; }
    }
}
