//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_order
    {
        public int ISBN { get; set; }
        public int Order_id { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<float> Total_price_sub { get; set; }
    
        public virtual book book { get; set; }
        public virtual order order { get; set; }
    }
}
